name: Build Kivy Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Linux Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential git zip unzip openjdk-17-jdk autoconf libtool \
          pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev \
          libtinfo5 cmake libffi-dev libssl-dev python3-setuptools

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Compilers
      run: |
        pip install --upgrade pip --break-system-packages
        pip install cython kivy buildozer --break-system-packages

    - name: Build APK (Debug Mode)
      run: |
        # Forces Buildozer to print everything live to the GitHub log console
        buildozer --verbose android debug
      env:
        APP_ANDROID_ACCEPT_SDK_LICENSE: "1"
        BUILDOZER_ALLOW_ORG_TEST_DOMAIN: "1"

    - name: Upload APK Package
      uses: actions/upload-artifact@v4
      with:
        name: MofidApp-Android-Package
        path: bin/*.apk

